#!/bin/sh
set -e

cd health-onboarding-form

echo "Running linter check..."
pnpm lint-staged

echo "Running lint fix..."
pnpm exec eslint --fix

echo "Running format update..."
pnpm exec prettier --write .
